# Generated by Django 3.0.3 on 2022-04-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0033_auto_20220305_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
