# Generated by Django 3.0.3 on 2022-04-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0037_chapters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'verbose_name': 'Chapters', 'verbose_name_plural': 'Chapters'},
        ),
    ]
