# Generated by Django 3.0.3 on 2022-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0038_auto_20220426_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('topic1', models.TextField()),
                ('topic2', models.TextField()),
                ('topic3', models.TextField()),
            ],
            options={
                'verbose_name': 'Topics',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='user',
        ),
    ]
