# Generated by Django 3.0.3 on 2022-04-26 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0039_auto_20220426_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
