# Generated by Django 3.0.3 on 2022-04-26 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0040_topics_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
