# Generated by Django 3.0.3 on 2022-04-28 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0042_auto_20220427_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Подтемы', 'verbose_name_plural': 'Подтемы'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='body1',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='body2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='body3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='topic1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='topic2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='topic3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
