# Generated by Django 4.0.4 on 2022-04-28 08:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0043_auto_20220428_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
