# Generated by Django 4.0.4 on 2022-04-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0045_alter_article_topic1_alter_article_topic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile_picture.jpg', null=True, upload_to='images/profile'),
        ),
    ]
