# Generated by Django 4.0.4 on 2022-05-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0047_quiz_result_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результаты', 'verbose_name_plural': 'Результаты'},
        ),
    ]
