# Generated by Django 4.0.4 on 2022-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0048_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile_picture.png', null=True, upload_to='images/profile'),
        ),
    ]
