# Generated by Django 4.0.4 on 2022-05-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0049_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профили'},
        ),
    ]
