# Generated by Django 4.0.4 on 2022-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0051_profile_auth_token_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile/default_profile_picture.png', null=True, upload_to='images/profile'),
        ),
    ]
