# Generated by Django 4.0.4 on 2022-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0052_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile/pfp.png', null=True, upload_to='images/profile'),
        ),
    ]
