# Generated by Django 4.0.4 on 2022-06-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0053_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='lectures',
            options={'verbose_name': 'Лекции', 'verbose_name_plural': 'Лекции'},
        ),
    ]
