# Generated by Django 4.0.4 on 2022-06-01 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0055_alter_lectures_text_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
