# Generated by Django 4.0.4 on 2022-06-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0058_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
    ]
