# Generated by Django 4.0.4 on 2022-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0059_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/img/pfp.png', null=True, upload_to='images/profile'),
        ),
    ]
