# Generated by Django 4.0.4 on 2023-04-18 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universystem', '0060_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollCource',
            new_name='EnrollCourse',
        ),
        migrations.RenameModel(
            old_name='Lectures_text',
            new_name='LecturesText',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/pfp.png', null=True, upload_to='images/profile'),
        ),
    ]
